name: Deployment
on:
  workflow_dispatch:

env:
  ARTIFACT_FILENAME: mint#${{ github.ref_name }}#${{ github.sha }}.zip

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'run tests -- ${{ env.ARTIFACT_FILENAME }}'

  deploy-dev:
    name: Deploy(Dev)
    needs: test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - run: echo 'dev deployment  -- ${{ vars.test }}'
      - run: echo 'ENV_FILENAME - ${{ vars.ENV_FILENAME }}'
      - run: echo 'AWS_CODEDEPLOY_DEPLOY_GROUP - ${{ vars.AWS_CODEDEPLOY_DEPLOY_GROUP }}'

  deploy-production:
    name: Deploy(Production)
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'production deployment -- ${{ vars.test }}'
      - run: echo 'ENV_FILENAME - ${{ vars.ENV_FILENAME }}'
      - run: echo 'AWS_CODEDEPLOY_DEPLOY_GROUP - ${{ vars.AWS_CODEDEPLOY_DEPLOY_GROUP }}'
